// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class NopCommercesuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loginwithvalidcredslogout() {
    driver.Navigate().GoToUrl("http://192.168.56.1:8777/");
    driver.Manage().Window.Size = new System.Drawing.Size(1255, 693);
    driver.FindElement(By.Id("customerlanguage")).Click();
    driver.FindElement(By.Id("customerlanguage")).Click();
    driver.FindElement(By.CssSelector("#customerlanguage > option:nth-child(2)")).Click();
    driver.FindElement(By.LinkText("Log in")).Click();
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("admin@userqa.com");
    driver.FindElement(By.Id("Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".login-button")).Click();
    Assert.That(driver.FindElement(By.LinkText("Log out")).Text, Is.EqualTo("Log out"));
    driver.FindElement(By.LinkText("Log out")).Click();
    driver.Close();
  }
  [Test]
  public void addnokialumiatocard() {
    driver.Navigate().GoToUrl("http://192.168.56.1:8777/");
    driver.Manage().Window.Size = new System.Drawing.Size(1290, 722);
    driver.FindElement(By.Id("customerlanguage")).Click();
    driver.FindElement(By.Id("customerlanguage")).Click();
    driver.FindElement(By.CssSelector("#customerlanguage > option:nth-child(2)")).Click();
    driver.FindElement(By.LinkText("Log in")).Click();
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("admin@userqa.com");
    driver.FindElement(By.Id("Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".login-button")).Click();
    js.ExecuteScript("window.scrollTo(0,102)");
    driver.FindElement(By.CssSelector(".item-box:nth-child(1) .title > a")).Click();
    driver.FindElement(By.LinkText("Cell phones")).Click();
    driver.FindElement(By.CssSelector(".item-box:nth-child(3) .product-box-add-to-cart-button")).Click();
    driver.FindElement(By.CssSelector(".cart-label")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".search-box-button"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    Assert.That(driver.FindElement(By.LinkText("Log out")).Text, Is.EqualTo("Log out"));
    driver.FindElement(By.LinkText("Log out")).Click();
    driver.Close();
  }
  [Test]
  public void changequantitygoodsincart() {
    driver.Navigate().GoToUrl("http://192.168.56.1:8777/");
    driver.Manage().Window.Size = new System.Drawing.Size(1259, 652);
    driver.FindElement(By.Id("customerlanguage")).Click();
    driver.FindElement(By.Id("customerlanguage")).Click();
    {
      var dropdown = driver.FindElement(By.Id("customerlanguage"));
      dropdown.FindElement(By.XPath("//option[. = 'EN']")).Click();
    }
    driver.FindElement(By.CssSelector("#customerlanguage > option:nth-child(2)")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.LinkText("Log in")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("admin@userqa.com");
    driver.FindElement(By.Id("Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".login-button")).Click();
    driver.FindElement(By.LinkText("Electronics")).Click();
    driver.FindElement(By.LinkText("Cell phones")).Click();
    driver.FindElement(By.CssSelector(".item-box:nth-child(3) img")).Click();
    driver.FindElement(By.Id("add-to-cart-button-20")).Click();
    driver.FindElement(By.CssSelector(".cart-label")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".table-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".table-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".table-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.Id("itemquantity44")).Click();
    driver.FindElement(By.Id("itemquantity44")).SendKeys("5");
    driver.FindElement(By.CssSelector(".master-wrapper-page")).Click();
    driver.FindElement(By.CssSelector(".update-cart-button")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".table-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".table-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".table-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.Name("updatecart")).Click();
    driver.FindElement(By.LinkText("Log out")).Click();
    driver.Close();
  }
  [Test]
  public void setuserdata() {
    driver.Navigate().GoToUrl("http://192.168.56.1:8777/");
    driver.Manage().Window.Size = new System.Drawing.Size(1193, 728);
    driver.FindElement(By.Id("customerlanguage")).Click();
    driver.FindElement(By.Id("customerlanguage")).Click();
    {
      var dropdown = driver.FindElement(By.Id("customerlanguage"));
      dropdown.FindElement(By.XPath("//option[. = 'EN']")).Click();
    }
    driver.FindElement(By.CssSelector("#customerlanguage > option:nth-child(2)")).Click();
    driver.FindElement(By.LinkText("Log in")).Click();
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("admin@userqa.com");
    driver.FindElement(By.Id("Password")).SendKeys("123456");
    driver.FindElement(By.CssSelector("form > .buttons")).Click();
    driver.FindElement(By.CssSelector(".login-button")).Click();
    driver.FindElement(By.LinkText("My account")).Click();
    driver.FindElement(By.Id("FirstName")).Click();
    driver.FindElement(By.Id("FirstName")).SendKeys("Pavel");
    driver.FindElement(By.Id("LastName")).Click();
    driver.FindElement(By.Id("LastName")).SendKeys("Loika");
    driver.FindElement(By.CssSelector(".fieldset:nth-child(1) > .form-fields")).Click();
    driver.FindElement(By.Id("save-info-button")).Click();
    driver.FindElement(By.LinkText("Log out")).Click();
    driver.Close();
  }
}
